import { HomeView } from './HomeView';
import {
  Login,
  DashboardView,
  ProfileView,
  SampleComponent,
  RegistrarSectionsListView,
  Page404,
  Page401,
  RegistrarManageStudentsView,
  RegistrarViewEnrolledView,
  RegistrarViewPastRecordsView,
  RegistrarAssignAdvisorySectionView,
  RegistrarAssignSubjectLoadView,
  RegistrarViewSubjectLoadView,
  RegistrarEditSubjectLoadView,
  TeacherViewSubjectLoadView,
  TeacherViewSubjectLoadByIdView,
  TeacherManageGradesView,
  TeacherComponentView,
  TeacherSubcomponentView,
  TeacherAddRecordView,
  TeacherSummaryPerQuarterView,
  TeacherEditRecordView,
  TeacherSummaryView,
} from './';

export default {
  path: '/',
  name: 'App',
  childRoutes: [
    { path: 'home-view', name: 'Home view', component: HomeView, isIndex: true },
    { path: '/login', name: 'Login', component: Login },
    { path: '/dashboard', name: 'Dashboard view', component: DashboardView },
    { path: '/profile', name: 'Profile view', component: ProfileView },
    { path: '/sampleComponent', name: 'Sample component', component: SampleComponent },
    {
      path: '/sectionslist',
      name: 'Registrar add section view',
      component: RegistrarSectionsListView,
    },
    { path: 'page404', name: 'Page 404', component: Page404 },
    { path: 'page401', name: 'Page 401', component: Page401 },
    {
      path: '/managestudents',
      name: 'Registrar enroll students view',
      component: RegistrarManageStudentsView,
    },
    {
      path: 'managestudents/viewenrolled/:id',
      name: 'Registrar view enrolled view',
      component: RegistrarViewEnrolledView,
    },
    {
      path: 'managestudents/viewpastrecords/:id',
      name: 'Registrar view past records view',
      component: RegistrarViewPastRecordsView,
    },
    {
      path: 'assignadvisorysection',
      name: 'Registrar assign advisory section view',
      component: RegistrarAssignAdvisorySectionView,
    },
    {
      path: 'assignsubjectload',
      name: 'Registrar assign subject load view',
      component: RegistrarAssignSubjectLoadView,
    },
    {
      path: 'assignsubjectload/viewload/:id',
      name: 'Registrar view subject load view',
      component: RegistrarViewSubjectLoadView,
    },
    {
      path: 'assignsubjectload/viewload/:id/edit/:id2',
      name: 'Registrar edit subject load view',
      component: RegistrarEditSubjectLoadView,
    },
    {
      path: '/viewsubjectload',
      name: 'Teacher view subject load view',
      component: TeacherViewSubjectLoadView,
    },
    {
      path: '/viewsubjectload/:id/:q',
      name: 'Teacher view subject load by id view',
      component: TeacherViewSubjectLoadByIdView,
    },
    {
      path: '/managegrades/:id/:q',
      name: 'Teacher manage grades view',
      component: TeacherManageGradesView,
    },
    {
      path: '/managegrades/:id/:q/:comp',
      name: 'Teacher component view',
      component: TeacherComponentView,
    },
    {
      path: '/managegrades/:id/:q/:comp/subcomp/:subcomp',
      name: 'Teacher subcomponent view',
      component: TeacherSubcomponentView,
    },
    {
      path: '/managegrades/:id/:q/:comp/subcomp/:subcomp/addrecord',
      name: 'Teacher add record view',
      component: TeacherAddRecordView,
    },
    {
      path: '/summaryreport/:id/:q',
      name: 'Teacher summary per quarter view',
      component: TeacherSummaryPerQuarterView,
    },
    {
      path: '/managegrades/:id/:q/:comp/subcomp/:subcomp/editrecord/:rec',
      name: 'Teacher edit record view',
      component: TeacherEditRecordView,
    },
    { path: '/summaryreportall/:id', name: 'Teacher summary view', component: TeacherSummaryView },
  ],
};
